In [1]:
import sqlite3, pandas as pd
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 50)
pd.set_option("display.width", None)
conn = sqlite3.connect("C:/Users/asus/Desktop/Datathon/panel_data/iett_data.db")
print("Hazir")

Hazir

In [2]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', 50)

df_ariza = pd.read_csv("C:/Users/asus/Desktop/Datathon/panel_data/temiz_veri/ariza_temiz.csv", low_memory=False)
print(f"Satir: {len(df_ariza):,} | Kolon: {len(df_ariza.columns)}")
df_ariza.sample(20).reset_index(drop=True)

Satir: 59,050 | Kolon: 34

,KAPINO,MARKA,MODEL,MODELYILI,ARACCINSI,ARACTIPI,KAPASITE,AZAMIYUKLUAGIRLIK,YAKITTURU,EMISYON,GARAJ,USTOPERATORADI,HATKODU,HATCINSI,HATUZUNLUK,SOFOR_SICILNO,ENLEM,BOYLAM,ARIZAKODU,ARIZAUSTKODTANIM,SONUCTIPI,IMDAT_TIP,CEKICITALEP,ZAYISEFERSAYISI,TOPLAM_SURE_DK,OLAYTARIHI,YIL,AY,GUN,HAFTASONU,ciddi_ariza,SAAT,DAKIKA,GUNLUK_SEFER_SAYISI
0,O3330,OTOKAR,KENT 290LF,2013.0,SOLO,Otobüs,94.0,18000.0,MOTORIN,EEV,SULTANGAZIGARAJI,İETT,36HT,İETT,30228.88,P_58787,"41,210431","28,697233",SEVİYE DÜZENLEME YAPMIYOR,SÜSPANSİYON SİSTEMİ ARIZALARI,Telefonla - Servis,İmdat gönderilmedi,0,0,14.3,2025-03-03 18:34:20.741,2025,3,3,0,0,18,34,6.0
1,M2950,MERCEDES,CITARO 0530,2006.0,SOLO,Otobüs,82.0,18000.0,MOTORIN,EUR,Şahinkaya,İETT,15A,KARMA,20105.12,P_56734,"41,173659","29,089074",FRENLER SIKIYOR,FREN ŞİKAYETLERİ,Oto Değişimi,İmdat gönderilmedi,0,0,33.3,2025-03-29 12:17:15.011,2025,3,29,1,1,12,17,5.0
2,O5880,OTOKAR,KENT 290LF,2013.0,SOLO,Otobüs,94.0,18000.0,MOTORIN,EEV,SULTANGAZIGARAJI,İETT,28T,KARMA,12164.65,P_34105,"41,020308","28,924492",SEVİYE DÜZENLEME YAPMIYOR,SÜSPANSİYON SİSTEMİ ARIZALARI,Telefonla - Garaj,İmdat gönderilmedi,0,0,119.1,2025-05-30 07:59:27.539,2025,5,30,0,1,7,59,2.0
3,K2410,KARSAN,AVANCITY S PLUS,2013.0,KORUKLU,Otobüs,148.0,27950.0,MOTORIN,EEV,KURTKÖY,İETT,19A,İETT,27910.55,P_56814,"40,976634","29,240173",SU HORTUMU PATLAK,SOĞUTMA SİSTEMİ ARIZASI,Oto Değişimi,İmdat gönderilmedi,0,0,101.1,2025-03-04 10:23:57.343,2025,3,4,0,1,10,23,7.0
4,K2916,KARSAN,AVANCITY S PLUS,2013.0,KORUKLU,Otobüs,148.0,27950.0,MOTORIN,EEV,KURTKÖY,İETT,18Ü,İETT,39311.77,P_59413,"40,980345","29,206699",VİTESLERE GEÇİŞTE VURUNTU YAPIYOR,OTOMATİK ŞANZIMAN ARIZALARI,Çekilerek - Garaj,İmdat gönderilmedi,0,1,111.6,2025-04-25 08:17:30.586,2025,4,25,0,1,8,17,4.0
5,M1152,MERCEDES,CONECTO G,2015.0,KORUKLU,Metrobüs,154.0,28000.0,MOTORIN,EUR,Hasanpaşa,İETT,34G,METROBÜS,31215.91,P_56348,"40,991784","29,037764",İÇ TUTAMAK ARIZASI,KAROSER ARIZALARI,Yol Ustası - Garaj,İmdat gönderilmedi,0,0,28.0,2025-05-03 11:27:49.000,2025,5,3,1,1,11,27,2.0
6,K5997,KARSAN,AVANCITY S PLUS,2013.0,KORUKLU,Otobüs,148.0,27950.0,MOTORIN,EEV,IKITELLIISLETTIRMEGARAJI2,İETT,79B,KARMA,38251.41,P_50948,"41,106254","28,747317",SEVİYE DÜZENLEME YAPMIYOR,SÜSPANSİYON SİSTEMİ ARIZALARI,Yol Ustası - Garaj,İmdat gönderilmedi,0,1,119.0,2025-03-18 18:29:45.342,2025,3,18,0,1,18,29,4.0
7,T3707,TEMSA,AVENUE LF CNG,2014.0,SOLO,Otobüs,97.0,18000.0,CNG,EEV,IKITELLIISLETTIRMEGARAJI2,İETT,HS3,İETT,16798.59,P_58806,"41,018485","28,797679",HASARLI - (SAĞ ARKA),KAROSER ARIZALARI,Telefonla - Servis,İmdat gönderilmedi,0,0,17.2,2025-02-19 10:44:48.017,2025,2,19,0,0,10,44,14.0
8,M3464,MERCEDES,CITARO 0530,2007.0,SOLO,Otobüs,82.0,18000.0,MOTORIN,EUR,Anadolu,İETT,11C,İETT,7764.83,P_56396,"41,031916","29,060922",SU HORTUMU PATLAK,SOĞUTMA SİSTEMİ ARIZASI,Yol Ustası - Servis,İmdat gönderilmedi,0,1,79.9,2025-04-02 17:33:42.693,2025,4,2,0,0,17,33,6.0
9,M3919,MERCEDES,CITARO 0530,2006.0,SOLO,Otobüs,82.0,18000.0,MOTORIN,EUR,Anadolu,İETT,11CÜ,İETT,18654.12,P_30465,"41,031776","29,060998",HARARET YÜKSELİYOR,SOĞUTMA SİSTEMİ ARIZASI,Yol Ustası - Servis,İmdat gönderilmedi,0,1,60.7,2025-02-03 06:11:42.631,2025,2,3,0,0,6,11,7.0
10,M3240,MERCEDES,CONECTO G,2012.0,KORUKLU,Otobüs,154.0,28000.0,MOTORIN,EUR,Anadolu,İETT,19SK,OAŞ,20450.80,P_9365,"41,007278","29,215422",AYNA AYARLARI,KAROSER ARIZALARI,Yol Ustası - Servis,İmdat gönderilmedi,0,0,56.0,2025-01-20 07:23:58.327,2025,1,20,0,0,7,23,10.0
11,K5799,KARSAN,AVANCITY S PLUS,2013.0,KORUKLU,Otobüs,148.0,27950.0,MOTORIN,EEV,KURTKÖY,İETT,19A,İETT,27910.55,P_63724,"41,008709","29,211272",Zamanında Müdahale Edilmeme,Destek,Çekilerek - Garaj,İmdat gönderilmedi,1,5,0.5,2025-03-14 17:57:48.000,2025,3,14,0,1,17,57,13.0
12,K4944,KARSAN,AVANCITY S PLUS,2013.0,KORUKLU,Otobüs,148.0,27950.0,MOTORIN,EEV,IKITELLIISLETTIRMEGARAJI2,İETT,MK22,İETT,20345.64,P_38897,"41,210328","28,715713",OTO ÇEKMİYOR,MOTOR ARIZALARI,Telefonla - Garaj,İmdat gönderilmedi,0,1,3.2,2025-05-01 07:47:21.161,2025,5,1,0,1,7,47,2.0
13,O6928,OTOKAR,KENT XL,2022.0,KORUKLU,Metrobüs,0.0,0.0,MOTORIN,Bilinmiyor,Hasanpaşa,İETT,34Z,METROBÜS,6872.67,P_33910,"41,066574","29,012920",KLİMA ÇALIŞMIYOR,KLİMA SİSTEMİ ARIZALARI,Yol Ustası - Garaj,İmdat gönderilmedi,0,0,51.6,2025-06-30 18:49:03.000,2025,6,30,0,1,18,49,7.0
14,M3213,MERCEDES,CONECTO G,2012.0,KORUKLU,Metrobüs,154.0,28000.0,MOTORIN,EUR,Hasanpaşa,İETT,34C,METROBÜS,16527.41,P_56996,"41,028212","28,923823",FAR LAMBA ARIZALARI,ELEKTRİK SİSTEMİ ARIZALARI,Kayıtçı - Garaj,İmdat gönderilmedi,0,0,6.8,2025-05-20 21:12:05.000,2025,5,20,0,0,21,12,9.0
15,M4366,MERCEDES,CONECTO G,2015.0,KORUKLU,Metrobüs,154.0,28000.0,MOTORIN,EUR,Hasanpaşa,İETT,34G,METROBÜS,31215.91,P_8509,"41,065661","29,013187",SU EKSİK,SOĞUTMA SİSTEMİ ARIZASI,Yol Ustası - Servis,İmdat gönderilmedi,0,0,21.1,2025-01-28 16:36:35.000,2025,1,28,0,0,16,36,11.0
16,B6333,BMC,PROCITY TR,2017.0,SOLO,Otobüs,97.0,18000.0,MOTORIN,EUR,IKITELLIGARAJI,İETT,MR51,İETT,31967.06,P_32036,"41,059701","28,732440",CAM ARIZALARI,KAROSER ARIZALARI,Oto Değişimi,İmdat gönderilmedi,0,1,91.7,2025-01-04 08:53:26.896,2025,1,4,1,1,8,53,3.0
17,B1839,BMC,PROCITY TR,2017.0,SOLO,Otobüs,97.0,18000.0,MOTORIN,EUR,IKITELLIGARAJI,İETT,78F,İETT,37600.36,P_35278,"41,108845","28,801174",FRENLER SIKIYOR,FREN ŞİKAYETLERİ,Oto Değişimi,İmdat gönderilmedi,0,1,103.2,2025-04-04 18:49:54.941,2025,4,4,0,1,18,49,8.0
18,M3267,MERCEDES,CAPACITY,2008.0,KORUKLU,Metrobüs,184.0,32000.0,MOTORIN,EUR,Edirnekapı,İETT,34BZ,METROBÜS,23740.99,P_38928,"41,014831","28,908206",DİFERANSİYEL KOVANI PATLAK,DİFERANSİYEL ARIZALARI,Çekilerek - Garaj,İmdat gönderilmedi,0,1,15.9,2025-05-16 19:36:37.000,2025,5,16,0,1,19,36,8.0
19,T4380,TEMSA,AVENUE LF CNG,2014.0,SOLO,Otobüs,97.0,18000.0,CNG,EEV,IKITELLIISLETTIRMEGARAJI2,İETT,MR54,İETT,21480.68,P_50804,"41,085659","28,722850",YAKIT İKMALİ,YAKIT ve ENJEKSİYON ARIZALARI,Oto Değişimi,İmdat gönderilmedi,0,0,16.5,2025-06-03 22:04:44.751,2025,6,3,0,1,22,4,15.0

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', 50)

df_model = pd.read_csv("C:/Users/asus/Desktop/Datathon/panel_data/temiz_veri/ariza_model.csv", low_memory=False)
print(f"Satir: {len(df_model):,} | Kolon: {len(df_model.columns)}")
df_model.sample(20).reset_index(drop=True)

Satir: 59,025 | Kolon: 25

,KAPINO,MARKA,MODEL,MODELYILI,ARACCINSI,KAPASITE,AZAMIYUKLUAGIRLIK,YAKITTURU,EMISYON,GARAJ,HATKODU,HATCINSI,HATUZUNLUK,SOFOR_SICILNO,ARIZAKODU,ARIZAUSTKODTANIM,AY,HAFTASONU,ciddi_ariza,SAAT,GUNLUK_SEFER_SAYISI,SONUCTIPI,IMDAT_TIP,TOPLAM_SURE_DK,OLAYTARIHI
0,M5645,MERCEDES,CAPACITY,2009.0,KORUKLU,184.0,32000.0,MOTORIN,EUR,Edirnekapı,34G,METROBÜS,31215.91,P_8277,HAVA KAÇAĞI-BORU PATLAK,BASINÇLI HAVA HATTI ARIZASI,1,0,1,6,1.0,Çekilerek - Garaj,İmdat gönderilmedi,44.2,2025-01-14 06:40:34.000
1,M3103,MERCEDES,CONECTO G,2012.0,KORUKLU,154.0,28000.0,MOTORIN,EUR,Hasanpaşa,34AS,METROBÜS,21331.46,P_5639,KÖRÜK BÜKÜLME KUMANDA HATASI,KWS SİSTEMİ ARIZALARI,5,0,0,18,12.0,Kayıtçı - Garaj,İmdat gönderilmedi,14.5,2025-05-20 18:06:05.000
2,K2413,KARSAN,AVANCITY S PLUS,2013.0,KORUKLU,148.0,27950.0,MOTORIN,EEV,IKITELLIISLETTIRMEGARAJI2,142F,İETT,10686.69,P_7106,SEVİYE DÜZENLEME YAPMIYOR,SÜSPANSİYON SİSTEMİ ARIZALARI,6,0,0,5,6.0,Telefonla - Servis,İmdat gönderilmedi,70.1,2025-06-18 05:49:29.291
3,K5795,KARSAN,AVANCITY S PLUS,2013.0,KORUKLU,148.0,27950.0,MOTORIN,EEV,KURTKÖY,18Ü,İETT,39311.77,P_56358,Zamanında Müdahale Edilmeme,Destek,5,0,1,15,9.0,Çekilerek - Garaj,İmdat gönderilmedi,207.1,2025-05-07 15:38:48.000
4,K5908,KARSAN,AVANCITY S PLUS,2013.0,KORUKLU,148.0,27950.0,MOTORIN,EEV,KURTKÖY,18K,İETT,32347.24,P_33479,HARARET VE SU EKSİK,SOĞUTMA SİSTEMİ ARIZASI,4,1,0,19,10.0,Yol Ustası - Servis,İmdat gönderilmedi,74.4,2025-04-19 19:18:08.001
5,M5590,MERCEDES,CAPACITY,2009.0,KORUKLU,184.0,32000.0,MOTORIN,EUR,Edirnekapı,34G,METROBÜS,31215.91,P_56580,KM HIZ SENSÖRÜ ARIZALI,ELEKTRİK SİSTEMİ ARIZALARI,3,0,1,17,8.0,Yol Ustası - Garaj,İmdat gönderilmedi,12.1,2025-03-19 17:29:25.000
6,M6509,MERCEDES,CITARO 0530 G,2006.0,KORUKLU,137.0,26278.0,MOTORIN,EUR,Şahinkaya,11ÇB,İETT,27273.35,P_28563,KLİMA SOĞUTMUYOR,KLİMA SİSTEMİ ARIZALARI,5,1,1,14,4.0,Oto Değişimi,İmdat gönderilmedi,65.4,2025-05-04 14:33:41.044
7,A4810,AKIA,LF25,2022.0,KORUKLU,0.0,0.0,MOTORIN,Bilinmiyor,Edirnekapı,34BZ,METROBÜS,23740.99,P_8787,SU EKSİK,SOĞUTMA SİSTEMİ ARIZASI,1,0,1,13,9.0,Yol Ustası - Garaj,İmdat gönderilmedi,84.8,2025-01-03 13:53:04.000
8,O6155,OTOKAR,KENT 290LF,2013.0,SOLO,94.0,18000.0,MOTORIN,EEV,KURTKÖY,131SB,İETT,18641.83,P_59720,ŞOFÖR EMNİYET KEMERİ ARIZASI,KAROSER ARIZALARI,5,0,0,7,11.0,Telefonla - Servis,İmdat gönderilmedi,24.5,2025-05-15 07:25:33.173
9,K3991,KARSAN,AVANCITY S PLUS,2013.0,KORUKLU,148.0,27950.0,MOTORIN,EEV,KURTKÖY,16S,İETT,39891.95,P_56779,KAPI HAVA KAÇAĞI ARIZASI,KAPI ARIZALARI,4,0,0,17,5.0,Yol Ustası - Servis,İmdat gönderilmedi,36.0,2025-04-07 17:29:24.872
10,M2988,MERCEDES,CITARO 0530 G,2006.0,KORUKLU,137.0,26278.0,MOTORIN,EUR,Şahinkaya,15F,KARMA,27169.88,P_38724,KAPI DONANIM HATASI,KAPI ARIZALARI,2,0,0,8,5.0,Yol Ustası - Servis,İmdat gönderilmedi,40.7,2025-02-28 08:17:05.982
11,O2768,OTOKAR,KENT 290LF,2013.0,SOLO,94.0,18000.0,MOTORIN,EEV,SULTANGAZIGARAJI,151,İETT,19709.98,P_33950,SU HORTUMU PATLAK,SOĞUTMA SİSTEMİ ARIZASI,2,0,0,16,14.0,Yol Ustası - Servis,İmdat gönderilmedi,43.1,2025-02-20 16:55:53.054
12,M6549,MERCEDES,CONECTO G,2012.0,KORUKLU,154.0,28000.0,MOTORIN,EUR,Anadolu,14B,KARMA,20735.86,P_35620,OTO ÇEKMİYOR,MOTOR ARIZALARI,4,0,0,19,9.0,Yol Ustası - Servis,İmdat gönderilmedi,108.2,2025-04-17 19:16:44.076
13,M3128,MERCEDES,CONECTO G,2012.0,KORUKLU,154.0,28000.0,MOTORIN,EUR,SULTANGAZIGARAJI,TM17,KARMA,10166.36,P_31461,OTO ÇEKMİYOR,MOTOR ARIZALARI,4,0,1,17,2.0,Yol Ustası - Garaj,İmdat gönderilmedi,79.3,2025-04-21 17:59:02.997
14,K3008,KARSAN,AVANCITY S PLUS,2013.0,KORUKLU,148.0,27950.0,MOTORIN,EEV,IKITELLIISLETTIRMEGARAJI2,79KM,İETT,39883.95,P_43864,KALORİFER HORTUMU VE BORUSU DELİK,ISITMA SİSTEMİ,1,1,0,14,10.0,Yol Ustası - Servis,IETT,123.5,2025-01-19 14:40:39.302
15,M3748,MERCEDES,CAPACITY,2009.0,KORUKLU,184.0,32000.0,MOTORIN,EUR,Edirnekapı,34AS,METROBÜS,21331.46,P_30903,KAPI CAMI KIRIK,KAPI ARIZALARI,3,1,0,19,10.0,Kayıtçı - Garaj,İmdat gönderilmedi,7.9,2025-03-22 19:41:14.000
16,T3618,TEMSA,AVENUE LF CNG,2014.0,SOLO,97.0,18000.0,CNG,EEV,IKITELLIISLETTIRMEGARAJI2,76,İETT,26201.22,P_51122,KLİMA ÇALIŞMIYOR,KLİMA SİSTEMİ ARIZALARI,6,0,0,6,7.0,Telefonla - Servis,İmdat gönderilmedi,8.5,2025-06-18 06:42:49.002
17,K4502,KARSAN,AVANCITY CNG,2013.0,SOLO,87.0,19000.0,CNG,EEV,Kağıthane,TM2,KARMA,8838.64,P_9563,KÖRÜK PATLAK,SÜSPANSİYON SİSTEMİ ARIZALARI,5,0,0,6,4.0,Yol Ustası - Servis,İmdat gönderilmedi,81.5,2025-05-19 06:03:29.109
18,O6073,OTOKAR,KENT 290LF,2013.0,SOLO,94.0,18000.0,MOTORIN,EEV,Yunus,KM41,İETT,12607.25,P_63287,MOTOR YAĞI EKSİK,BASINÇLI MOTOR YAĞI SİSTEMİ,3,0,0,7,16.0,Yol Ustası - Servis,İmdat gönderilmedi,25.7,2025-03-17 07:05:36.055
19,K4572,KARSAN,AVANCITY S PLUS,2013.0,KORUKLU,148.0,27950.0,MOTORIN,EEV,KURTKÖY,18Ü,İETT,39311.77,P_60414,"KAPI TESİSATI [SİGORTASI,ROLE,İKAZ IŞIKLARI]",KAPI ARIZALARI,4,0,0,7,6.0,Yol Ustası - Servis,İmdat gönderilmedi,12.0,2025-04-14 07:38:30.834

In [4]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', 50)

df_kaza = pd.read_csv("C:/Users/asus/Desktop/Datathon/panel_data/temiz_veri/kaza_temiz.csv")
print(f"Satir: {len(df_kaza):,} | Kolon: {len(df_kaza.columns)}")
df_kaza.sample(20).reset_index(drop=True)

Satir: 3,039 | Kolon: 69

,KAZASAAT,ILCE,ENLEM,BOYLAM,YARALISURUCU,OLUMSURUCU,OLUMYOLCU,YARALIYOLCU,OLUMYAYA,YARALIYAYA,OLUMSIVIL,YARALISIVIL,HIZSON,YAKINDURAKKODU,GUZERGAHKODU,GUZERGAHADI,YON,GUZERGAHDEPAR,HATADI,HATKODU,DURUM,UZUNLUK,SURE,GARAJKODU,GARAJADI,OPERATOR,DURAKKODU,DURAKADI,DURAKTIPI,IL,MAHALLE,YONBILGISI,KUSURGRUBU,TARIH,YIL,AY,GUN,CEYREK,HAFTA,HAFTASONU,HATGARAJI,HATCINSI,HATUZUNLUK,HATILCE,HATSURESI,KAPINO,MARKA,MODEL,MODELYILI,KAPASITE,YAKITTURU,GARAJ,ARACCINSI,ARACTIPI,KOLTUKSAYISI,AZAMIKISISAYI,AZAMIYUKLUAGIRLIK,EMISYON,SICILNO,TIP,MESLEK,KATEGORIADI,HAVADURUMU,YOLDURUMU,KAVSAKDURUMU,TRAFIKDURUMU,SERITKENDI,KAZANOKTA,HAREKETYONU
0,2025-03-09 13:40:26.983,Bilinmiyor,0.000000,0.000000,0,0,0,0,0,0,0,0,0.0,Bilinmiyor,43R_G_D3045,RUMELİ HİSARÜSTÜ - RUMELİHİSARÜSTÜ,GİDİŞ,3045,RUMELİ HİSARÜSTÜ - KABATAŞ,43R,1.0,18385.11,2668.78,Bilinmiyor,Bilinmiyor,İstanbul Halk Ulaşım,NaN,Bilinmiyor,Bilinmiyor,İstanbul,Bilinmiyor,Bilinmiyor,KUSUR_BELIRLENMEDI,2025-03-09,2025,3,9,1,10,1,SULTANGAZİ GARAJI,KARMA,9778.67,Sarıyer,2668.78,A5034,Bilinmiyor,AKIA ULTRA LF12,2014,100.0,Bilinmiyor,Bilinmiyor,Solo -12m,Bilinmiyor,29.0,94.0,18000.0,Bilinmiyor,P_27385,IETT,Şoför,Araca Çarpma,Güneşli,Normal,Tek Yön,Normal : Yasal hız limitini engelleyen faktör yok,Durakta,Sol arka köşe,Duruyor
1,2025-01-09 07:45:00.000,Küçükçekmece,41.024384,28.796398,0,0,0,0,0,0,0,0,0.0,124231,89K_G_D4231,KANUNİ SULTAN SÜLEYMAN - KARTALTEPE,GİDİŞ,4231,K.S.S. HASTANESİ - AKSARAY,89K,1.0,21174.57,3073.73,Bilinmiyor,Bilinmiyor,İst Halk Otobüs,124231.0,PAZAR YOLU,AÇIK DURAK,İstanbul,İnönü,İNÖNÜ MAHALLESİ,KUSUR_BELIRLENMEDI,2025-01-09,2025,1,9,1,2,0,IKITELLIGARAJI,KARMA,26185.36,Küçükçekmece,7496.72,C7461,Bilinmiyor,TEMSA AVENUE LF,2014,106.0,Bilinmiyor,Bilinmiyor,Solo -12m,Bilinmiyor,29.0,94.0,18000.0,Bilinmiyor,P_63450,IETT,Şoför,Araca Çarpma,Akşam,Normal,Gidiş-Geliş yol,Kontrol edilmedi,Araç şerit çizgisi üzerinde iken kaza olmuştur,Sağ cephe,İleri yönlü Sağa doğru hafif açılı manevra hal...
2,2025-06-08 16:17:00.000,Zeytinburnu,40.985336,28.904385,0,0,0,0,0,0,0,0,7.0,109211,93T_G_D5174,ZEYTİNBURNU - HARBİYE ASKERİ MÜZE,GİDİŞ,5174,ZEYTİNBURNU - TAKSİM,93T,1.0,36881.90,5353.84,Bilinmiyor,Bilinmiyor,İst Elit Kooperatif,109211.0,ŞEHİT ŞUAYİP SEFEROĞLU,İETTBAYRAK,İstanbul,Nuripaşa,TOPKAPI,KUSUR_BELIRLENMEDI,2025-06-08,2025,6,8,2,23,1,TOPKAPI(TT),KARMA,18761.40,Zeytinburnu,5353.84,A7724,Bilinmiyor,TEMSA,2014,108.0,Bilinmiyor,Bilinmiyor,Solo -12m,Bilinmiyor,29.0,94.0,18000.0,Bilinmiyor,P_38333,IETT,Şoför,Araca Çarpma,Güneşli,Normal,Bölünmüş yol,Kontrol edilmedi,Araç kendi şeridi sınırında iken kaza olmuştur,Sağ cephe,İleri yönlü Sağa doğru hafif açılı manevra hal...
3,2025-04-04 19:14:00.000,Pendik,40.873974,29.282976,0,0,0,0,0,0,0,0,24.0,208232,133K_G_D0,KANARYA CADDESİ - KARTAL,GİDİŞ,0,KURTKÖY SANAYİ MAHALLESİ / KAVAKPINAR - KARTAL,133K,1.0,20890.42,3032.49,G_KRT,KURTKOYGARAJI,İETT,208232.0,KAVAKPINAR DÖRTYOL,CCMODERN,İstanbul,Kavakpınar,PENDİK,Yaya Kusurları,2025-04-04,2025,4,4,2,14,0,Yunus (Park),İETT,20890.42,Pendik,6121.25,O5269,OTOKAR,KENT 290LF,2013,94.0,MOTORIN,KURTKÖY,SOLO,Otobüs,29.0,94.0,18000.0,EEV,P_56176,IETT,Şoför,Yayaya Çarpma,Bulutlu,Normal,Gidiş-Geliş yol,Normal : Yasal hız limitini engelleyen faktör yok,Araç bir bütün olarak kendi şeridi ortasında i...,Sol Ön köşe,Düz şeridinde ileri doğru
4,2025-05-08 08:48:00.000,Ümraniye,41.020252,29.123636,0,0,0,0,0,1,0,0,22.0,214161,13_D_D0,KADIKÖY - BATI ATAŞEHİR PERONLAR,DÖNÜŞ,0,ATAŞEHİR / ÇAKMAK MAHALLESİ - KADIKÖY,13,1.0,22422.70,3254.93,G_AND,ANADOLUGARAJI,Özulaş,214161.0,ÇAKMAK MERKEZ CAMİİ,İETTBAYRAK,İstanbul,Çakmak,ÜSKÜDAR 13A,Yaya Kusurları,2025-05-08,2025,5,8,2,19,0,ANADOLUGARAJI,ÖHO,23316.69,Ataşehir,6639.61,C1910,MERCEDES,MERCEDES CONECTO,2017,104.0,MOTORIN,Bilinmiyor,Solo -12m,Otobüs,29.0,82.0,18000.0,EUR,P_36100,IETT,Şoför,Yayaya Çarpma,Sabah,Normal,Tek Yön,Kontrol edilmedi,Araç bir bütün olarak kendi şeridi ortasında i...,Sağ ön köşe,Düz şeridinde ileri doğru
5,2025-04-15 11:48:49.070,Bilinmiyor,NaN,NaN,0,0,0,0,0,0,0,0,0.0,Bilinmiyor,79Y_D_D0,YENİBOSNA METRO - KAYABAŞI KİPTAŞ PERON,DÖNÜŞ,0,KAYABAŞI KİPTAŞ / KAYAŞEHİR - YENİBOSNA METRO,79Y,1.0,27988.56,4062.88,G_IKT,IKITELLIGARAJI,İETT,NaN,Bilinmiyor,Bilinmiyor,İstanbul,Bilinmiyor,Bilinmiyor,KUSUR_BELIRLENMEDI,2025-04-15,2025,4,15,2,15,0,IKITELLIGARAJI,İETT,26673.70,Başakşehir,7934.90,B6980,BMC,PROCITY TR,2017,97.0,MOTORIN,IKITELLIGARAJI,SOLO,Otobüs,26.0,97.0,18000.0,EUR,P_63592,IETT,Şoför,Diğer araçlar,Güneşli,Normal,Gidiş-Geliş yol,Kontrol edilmedi,Araç bir bütün olarak kendi şeridi ortasında i...,Ön cam,Düz şeridinde ileri doğru
6,2025-01-15 15:00:00.000,Ümraniye,41.020850,29.121880,0,0,0,0,0,0,0,0,14.0,222262,131_G_D0,SULTANBEYLİ PERONLAR - ESTERGON CADDESİ,GİDİŞ,0,SULTANBEYLİ - ÜMRANİYE,131,0.0,26168.19,3798.59,G_KRT,KURTKOYGARAJI,İETT,222262.0,ÇAKMAK KÖPRÜSÜ,CCMODERN,İstanbul,Fatih Sultan Mehmet,ÜSKÜDAR,KUSUR_BELIRLENMEDI,2025-01-15,2025,1,15,1,3,0,SARIGAZIGARAJI,OAŞ,26168.19,Sultanbeyli,7724.85,O3336,OTOKAR,KENT 290LF,2013,94.0,MOTORIN,KURTKÖY,SOLO,Otobüs,29.0,94.0,18000.0,EEV,P_60413,IETT,Şoför,Araca Çarpma,Yağmurlu,Yağış Kaygan,Bölünmüş yol,Kontrol edilmedi,Araç kendi şeridi sınırında iken kaza olmuştur,Sağ ayna,Düz şeridinde ileri doğru
7,2025-05-27 09:23:00.000,Küçükçekmece,41.056572,28.792410,0,0,0,0,0,0,0,0,8.0,125382,89F_D_D0,İSTOÇ 41.ADA - KÜÇÜKÇEKMECE MARMARAY,DÖNÜŞ,0,KÜÇÜKÇEKMECE-İSTOÇ,89F,1.0,18396.13,2670.41,G_IKT,IKITELLIGARAJI,İETT,125382.0,ATATÜRK MAHALLESİ,İETTBAYRAK,İstanbul,Atatürk,ATAKENT 2.ETAP,KUSUR_BELIRLENMEDI,2025-05-27,2025,5,27,2,21,0,IKITELLIGARAJI,İETT,18491.91,Küçükçekmece,5180.56,B5624,BMC,PROCITY TR,2017,97.0,MOTORIN,IKITELLIGARAJI,SOLO,Otobüs,26.0,97.0,18000.0,EUR,P_55581,IETT,Şoför,Araca Çarpma,Güneşli,Normal,Bölünmüş yol,Kontrol edilmedi,Araç şerit çizgisi üzerinde iken kaza olmuştur,Ön cephe,İleri yönlü Sağa doğru hafif açılı manevra hal...
8,2025-05-13 09:04:00.000,Tuzla,40.839160,29.369660,0,0,0,0,0,0,0,0,0.0,229592,130Ş_G_D0,ŞİFA SONDURAK - KADIKÖY,GİDİŞ,0,ŞİFA MAHALLESİ - KADIKÖY,130Ş,1.0,42387.13,6152.97,Bilinmiyor,Bilinmiyor,Öztaş Ulaşım,229592.0,SUMRU SOKAK,İETTBAYRAK,İstanbul,Mimar Sinan,ŞEKERPINAR,KUSUR_BELIRLENMEDI,2025-05-13,2025,5,13,2,19,0,Yunus (Park),ÖHO,42387.13,Çayırova,12152.40,C7588,Bilinmiyor,OTOKAR KENT,2017,99.0,Bilinmiyor,Bilinmiyor,Solo -12m,Bilinmiyor,29.0,94.0,18000.0,Bilinmiyor,P_62728,IETT,Şoför,Araca Çarpma,Bulutlu,Normal,Bölünmüş yol,Kontrol edilmedi,Araç bir bütün olarak kendi şeridi ortasında i...,Sol ayna,Düz şeridinde ileri doğru
9,2025-06-30 20:35:00.000,Kadıköy,40.958202,29.085215,0,0,0,0,0,0,0,1,44.0,224962,4_G_D0,MALTEPE PERONLAR - İSKELE,GİDİŞ,0,MALTEPE SAHİL - KADIKÖY,4,1.0,26608.46,3862.50,G_KRT,KURTKOYGARAJI,İETT,224962.0,TAN SOKAK,İETTBAYRAK,İstanbul,Suadiye,KADIKÖY,Sürücü Kusurları,2025-06-30,2025,6,30,2,26,0,Yunus (Park),OAŞ,26608.46,Maltepe,3862.50,O2305,OTOKAR,KENT 290LF,2013,94.0,MOTORIN,KURTKÖY,SOLO,Otobüs,29.0,94.0,18000.0,EEV,P_64059,IETT,Şoför,Araca Çarpma,Akşam,Normal,Tek Yön,Kontrol edilmedi,Araç şerit çizgisi üzerinde iken kaza olmuştur,Sağ ön köşe,Düz şeridinde ileri doğru
10,2025-06-02 06:25:41.171,Sultangazi,41.093980,28.907309,0,0,0,0,0,0,0,0,0.0,107051,42Z_G_D0,HACIOSMAN METRO - KAZIM KARABEKİR,GİDİŞ,0,HACIOSMAN METRO - KAZIM KARABEKİR,42Z,1.0,10715.36,1555.47,G_STGZ,SULTANGAZİ GARAJI,İETT,107051.0,SU KEMERİ,İETTBAYRAK,İstanbul,75. Yıl,YUNUS EMRE MAH.,KUSUR_BELIRLENMEDI,2025-06-02,2025,6,2,2,22,0,SULTANGAZİ GARAJI,İETT,10715.36,Sarıyer,1555.47,O5942,OTOKAR,KENT 290LF,2013,94.0,MOTORIN,SULTANGAZIGARAJI,SOLO,Otobüs,29.0,94.0,18000.0,EEV,P_9671,IETT,Şoför,Araca Çarpma,Güneşli,Normal,Bölünmüş yol,Kontrol edilmedi,Araç şerit çizgisi üzerinde iken kaza olmuştur,Sağ arka köşe,Duruyor
11,2025-03-16 19:30:00.000,Başakşehir,41.099453,28.774872,0,0,0,0,0,0,0,0,0.0,177972,79B_G_D7749,KAYAŞEHİR - BAKIRKÖY,GİDİŞ,7749,KAYAŞEHİR - BAKIRKÖY,79B,1.0,74300.06,10785.53,G_ISL2,IKITELLIISLETTIRMEGARAJI2,İETT,177972.0,NİDAPARK,DİĞER,İstanbul,Başakşehir,KAYAŞEHİR,KUSUR_BELIRLENMEDI,2025-03-16,2025,3,16,1,11,1,IKITELLIGARAJI,KARMA,38251.41,Başakşehir,10756.68,K2262,KARSAN,AVANCITY S PLUS,2013,148.0,MOTORIN,IKITELLIISLETTIRMEGARAJI2,KORUKLU,Otobüs,41.0,148.0,27950.0,EEV,P_61463,IETT,Şoför,Araca Çarpma,Bulutlu,Normal,Tek Yön,Kaldırım-Şerit Usulsüz Parklanma,Araç bir bütün olarak kendi şeridi ortasında i...,Arka cephe,Duruyor
12,2025-03-10 06:07:00.000,Beşiktaş,41.082584,29.038355,0,0,0,0,0,0,0,0,30.0,189361,59RS_D_D0,RUMELİ HİSARÜSTÜ - SARIYER,DÖNÜŞ,0,SARIYER - RUMELİ HİSARÜSTÜ,59RS,1.0,18621.27,2703.08,G_KAG,KAGITHANEGARAJI,İETT,189361.0,BASIN SİTESİ-HUZUREVİ,CCMODERN,İstanbul,Etiler,R.HİSARÜSTÜ,KUSUR_BELIRLENMEDI,2025-03-10,2025,3,10,1,10,0,SULTANGAZİ GARAJI,KARMA,19270.69,Sarıyer,5500.46,K2791,KARSAN,AVANCITY CNG,2013,87.0,CNG,Kağıthane,SOLO,Otobüs,27.0,87.0,19000.0,EEV,P_36099,IETT,Şoför,Araca Çarpma,Sabah,Normal,Gidiş-Geliş yol,Kontrol edilmedi,Araç kendi şeridi sınırında iken kaza olmuştur,Sağ cephe,Düz şeridinde ileri doğru
13,2025-04-05 16:18:45.207,Bilinmiyor,NaN,NaN,0,0,0,0,0,0,0,0,0.0,Bilinmiyor,34BZ_D_D0,ZİNCİRLİKUYU - B.SONDURAK,DÖNÜŞ,0,BEYLİKDÜZÜ - ZİNCİRLİKUYU,34BZ,1.0,35178.76,5106.62,G_HSP,HASANPASAGARAJI,İETT,NaN,Bilinmiyor,Bilinmiyor,İstanbul,Bilinmiyor,Bilinmiyor,KUSUR_BELIRLENMEDI,2025-04-05,2025,4,5,2,14,1,TOPKAPI(TT),METROBÜS,23740.99,Fatih,8552.91,M6786,MERCEDES,CONECTO G,2015,154.0,MOTORIN,Hasanpaşa,KORUKLU,Metrobüs,34.0,154.0,28000.0,EUR,P_6581,IETT,Şoför,Yayaya Çarpma,Bilinmiyor,Bilinmiyor,Bilinmiyor,Bilinmiyor,Bilinmiyor,Bilinmiyor,Bilinmiyor
14,2025-04-19 21:04:00.000,Kadıköy,40.989944,29.079836,0,0,0,0,0,0,0,0,0.0,206492,14A_D_D0,KADIKÖY - ÖZYEĞİN ÜNİVERSİTESİ ALT KAPI,DÖNÜŞ,0,ÖZYEĞİN ÜNİVERSİTESİ / ALEMDAĞ - KADIKÖY,14A,1.0,30922.39,4488.72,G_SRG,SARIGAZIGARAJI,İst Elit Kooperatif,206492.0,HASTANE,CCMODERN,İstanbul,Merdivenköy,TUZLA,KUSUR_BELIRLENMEDI,2025-04-19,2025,4,19,2,16,1,SARIGAZIGARAJI,OAŞ,32067.48,Çekmeköy,9143.70,C1720,OTOKAR,MERCEDES,2025,105.0,MOTORIN,Bilinmiyor,Solo -12m,Otobüs,29.0,94.0,18000.0,EEV,P_29656,IETT,Şoför,Araca Çarpma,Akşam,Normal,Bölünmüş yol,Kontrol edilmedi,Araç bir bütün olarak kendi şeridi ortasında i...,Sol cephe,Düz şeridinde ileri doğru
15,2025-06-05 18:16:00.000,Sultangazi,41.106514,28.860363,0,0,0,0,0,0,0,0,15.0,105301,36V_D_D0,VEZNECİLER - ÇİMEN CAMİ,DÖNÜŞ,0,YAYLA MAHALLESİ - VEZNECİLER,36V,1.0,22154.39,3215.96,G_TPK,TOPKAPI(TT),İETT,105301.0,İBRAHİM YILDIZ,İETTBAYRAK,İstanbul,İsmetpaşa,EDİRNEKAPI,KUSUR_BELIRLENMEDI,2025-06-05,2025,6,5,2,23,0,TOPKAPI(TT),İETT,23495.25,Sultangazi,6626.57,A9578,AKIA,ULTRA LF12,2024,0.0,MOTORIN,Topkapı,SOLO,Otobüs,0.0,0.0,0.0,EEV,P_34600,IETT,Şoför,Araca Çarpma,Güneşli,Normal,Tek Yön,Kontrol edilmedi,Araç şerit çizgisi üzerinde iken kaza olmuştur,Sol cephe,İleri yönlü sola doğru hafif açılı manevra hal...
16,2025-04-27 10:37:00.000,Beyoğlu,41.045380,28.944002,0,0,0,0,0,0,0,0,36.0,120102,50E_G_D1072,ALİBEYKÖY METRO - EMİNÖNÜ,GİDİŞ,1072,ALİBEYKÖY - EMİNÖNÜ,50E,1.0,20411.08,2962.90,G_KAG,KAGITHANEGARAJI,İstanbul Halk Ulaşım,120102.0,HALICIOĞLU - FATİH SULTAN MEHMET VAKIF ÜNİVERS...,CCMODERN,İstanbul,Halıcıoğlu,SÜTLÜCE,KUSUR_BELIRLENMEDI,2025-04-27,2025,4,27,2,17,1,KAGITHANEGARAJI,KARMA,10721.47,Eyüpsultan,3007.71,A1727,KARSAN,BMC,2012,102.0,CNG,Bilinmiyor,Solo -12m,Otobüs,27.0,87.0,19000.0,EEV,P_64103,IETT,Şoför,Araca Çarpma,Bulutlu,Normal,Bölünmüş yol,Kontrol edilmedi,Araç bir bütün olarak kendi şeridi ortasında i...,Sağ ön köşe,Düz şeridinde ileri doğru
17,2025-05-09 07:47:00.000,Esenyurt,41.034670,28.647160,0,0,0,0,0,0,0,0,10.0,127022,HT29_G_D3704,KIRAÇ YOLU - HARAMİDERE,GİDİŞ,3704,KIRAÇ YOLU - AVCILAR METROBÜS,HT29,1.0,11438.54,1660.44,G_IKT,IKITELLIGARAJI,İETT,127022.0,KIRAÇ KÖYÜ,AÇIK DURAK,İstanbul,İstiklal,ESENYURT-KIRAÇ,KUSUR_BELIRLENMEDI,2025-05-09,2025,5,9,2,19,0,IKITELLIGARAJI,İETT,17162.07,Esenyurt,5074.83,B6047,BMC,PROCITY TR,2017,97.0,MOTORIN,IKITELLIGARAJI,SOLO,Otobüs,26.0,97.0,18000.0,EUR,P_63592,IETT,Şoför,Araca Çarpma,Güneşli,Normal,Bölünmüş yol,Kontrol edilmedi,Araç bir bütün olarak kendi şeridi ortasında i...,Sağ cephe,Düz şeridinde ileri doğru
18,2025-05-26 10:44:00.000,Güngören,41.026024,28.872044,0,0,0,0,0,0,0,0,13.0,124772,98G_G_D5645,GİYİMKENT - BAKIRKÖY,GİDİŞ,5645,GİYİMKENT / TURGUTREİS - BAKIRKÖY,98G,1.0,37529.09,5447.75,G_STGZ,SULTANGAZİ GARAJI,İETT,124772.0,GÜNGÖREN,İETTBAYRAK,İstanbul,Merkez,BAĞCILAR,KUSUR_BELIRLENMEDI,2025-05-26,2025,5,26,2,21,0,TOPKAPI(TT),İETT,19027.01,Esenler,5510.77,O4155,OTOKAR,KENT 290LF,2013,94.0,MOTORIN,SULTANGAZIGARAJI,SOLO,Otobüs,29.0,94.0,18000.0,EEV,P_9076,IETT,ÇAYCI,Araca Çarpma,Yağmurlu,Yağış Kaygan,Bölünmüş yol,Normal : Yasal hız limitini engelleyen faktör yok,Araç şerit çizgisi üzerinde iken kaza olmuştur,Sağ cephe,İleri yönlü Sağa doğru hafif açılı manevra hal...
19,2025-01-06 14:06:00.000,Ataşehir,40.978780,29.133549,0,0,0,0,0,0,0,0,0.0,226592,14KS_D_D0,KOZYATAĞI METRO - SULTANBEYLİ PERONLAR,DÖNÜŞ,0,SULTANBEYLİ GÖLET - KOZYATAĞI METRO,14KS,1.0,25289.95,3671.13,Bilinmiyor,Bilinmiyor,İst Halk Otobüs,226592.0,İETT GARAJI,CCMODERNDR,İstanbul,İnönü,KAYIŞDAĞI,Sürücü Kusurları,2025-01-06,2025,1,6,1,1,0,KURTKOYGARAJI,KARMA,27475.90,Sultanbeyli,7659.54,C1641,Bilinmiyor,GÜLERYÜZ COBRA GD 272,2021,92.0,Bilinmiyor,Bilinmiyor,Solo -12m,Bilinmiyor,29.0,94.0,18000.0,Bilinmiyor,P_11835,IETT,Entegrasyon: Varsayılan p,Araca Çarpma,Güneşli,Normal,Durakta,Normal : Yasal hız limitini engelleyen faktör yok,Durakta,Sol arka köşe,Duruyor

In [5]:
df_kriz = pd.read_csv("C:/Users/asus/Desktop/Datathon/KRİZ/DATA/kriz_temiz.csv", encoding="utf-8-sig", low_memory=False)
print(f"Satir: {len(df_kriz):,} | Kolon: {len(df_kriz.columns)}")
df_kriz.head(10)

Satir: 3,637 | Kolon: 36

,FID,ID,SIDKAYITTARIHI,KAYITZAMANI,SIDDURAK,SIDKRIZSABLON,BASLAMATARIHI,BITISTARIHI,VARISTARIHI,KRIZTIPID,KRIZTIPTANIM,EYLEMTIPID,EYLEMTIPTANIM,KRIZSEVIYEID,TARIH,YIL,AY,GUN,CEYREK,HAFTA,HAFTASONU,DURAKKODU,DURAKADI,DURAKTIPI,FIZIKIDURUM,ENGELLIRAMPA,IL,ILCE,MAHALLE,DURAK_DURUM,YONBILGISI,SABLON_ID,SABLONADI,KRIZTIPADI,KRIZEYLEMTIPID,KRIZEYLEMTIPADI
0,33161787,80174,20250101,03:01:01,12459.0,10,2025-01-01 03:52:01.000,2025-01-01 04:05:57.681,2025-01-01 04:05:53.113,445,DİĞER OLAY,411,Normal Çalışma,0,2025-01-01,2025,1,1,1,1,0,900292.0,CENNET MAHALLESİ,ISTASYON,KAPALI,Var,İstanbul,Küçükçekmece,Cennet,1.0,ZİNCİRLİKUYU,578,DİĞER OLAY & NORMAL ÇALIŞMA,DİĞER OLAY,411.0,Normal Çalışma
1,33161789,80180,20250101,12:01:31,10582.0,26,2025-01-01 12:29:31.000,2025-01-01 12:31:32.658,2025-01-01 12:31:28.636,435,İSTASYON DIŞI ARIZA,411,Normal Çalışma,0,2025-01-01,2025,1,1,1,1,0,900112.0,OKMEYDANI HASTANE,ISTASYON,KAPALI,Var,İstanbul,Kağıthane,Gürsel,1.0,ZİNCİRLİKUYU,565,İSTASYON DIŞI ARIZA & NORMAL ÇALIŞMA,İSTASYON DIŞI ARIZA,411.0,Normal Çalışma
2,33161790,80181,20250101,13:01:54,15190.0,25,2025-01-01 13:16:54.000,2025-01-01 13:17:03.752,2025-01-01 13:16:58.318,436,İSTASYON DIŞI KAZA,411,Normal Çalışma,0,2025-01-01,2025,1,1,1,1,0,900012.0,SÖĞÜTLÜÇEŞME,ISTASYON,KAPALI,Var,İstanbul,Kadıköy,Zühtüpaşa,1.0,SON DURAK,568,İSTASYON DIŞI KAZA & NORMAL ÇALIŞMA,İSTASYON DIŞI KAZA,411.0,Normal Çalışma
3,33161791,80182,20250101,14:01:11,10583.0,26,2025-01-01 14:13:08.000,2025-01-01 14:13:19.537,2025-01-01 14:13:14.688,435,İSTASYON DIŞI ARIZA,411,Normal Çalışma,0,2025-01-01,2025,1,1,1,1,0,900192.0,CEVİZLİBAĞ,ISTASYON,KAPALI,Var,İstanbul,Zeytinburnu,Maltepe,1.0,ZİNCİRLİKUYU,565,İSTASYON DIŞI ARIZA & NORMAL ÇALIŞMA,İSTASYON DIŞI ARIZA,411.0,Normal Çalışma
4,33161792,80186,20250101,20:01:42,3466.0,10,2025-01-01 20:06:41.000,2025-01-01 20:06:57.239,2025-01-01 20:06:53.030,445,DİĞER OLAY,411,Normal Çalışma,0,2025-01-01,2025,1,1,1,1,0,900072.0,15 TEMMUZ ŞEHİTLER KÖPRÜSÜ,ISTASYON,AÇIK,Var,İstanbul,Üsküdar,Beylerbeyi,1.0,SÖĞÜTLÜÇEŞME,578,DİĞER OLAY & NORMAL ÇALIŞMA,DİĞER OLAY,411.0,Normal Çalışma
5,33162101,80176,20250101,06:01:14,1970.0,3,2025-01-01 06:10:14.000,2025-01-02 06:29:07.446,2025-01-02 06:29:02.815,438,BAKIM & ONARIM,99,Tek Şeritten Çalışma,0,2025-01-01,2025,1,1,1,1,0,900222.0,İNCİRLİ,ISTASYON,KAPALI,Var,İstanbul,Bahçelievler,Bahçelievler,1.0,ZİNCİRLİKUYU,561,BAKIM ONARIM & TEK ŞERİTTEN ÇALIŞMA,BAKIM & ONARIM,99.0,Tek Şeritten Çalışma
6,33163626,80161,20250101,18:01:53,1972.0,26,2025-01-01 18:27:53.000,2025-01-01 18:28:10.218,2025-01-01 18:28:05.006,435,İSTASYON DIŞI ARIZA,411,Normal Çalışma,0,2025-01-01,2025,1,1,1,1,0,900212.0,ZEYTİNBURNU,ISTASYON,KAPALI,Var,İstanbul,Güngören,Abdurrahman Nafiz Gürman,1.0,ZİNCİRLİKUYU,565,İSTASYON DIŞI ARIZA & NORMAL ÇALIŞMA,İSTASYON DIŞI ARIZA,411.0,Normal Çalışma
7,33164017,80153,20250101,00:01:58,8984.0,26,2025-01-01 00:19:58.000,2025-01-01 00:20:53.001,2025-01-01 00:20:38.173,435,İSTASYON DIŞI ARIZA,411,Normal Çalışma,0,2025-01-01,2025,1,1,1,1,0,900432.0,BEYKENT,ISTASYON,KAPALI,Var,İstanbul,Esenyurt,Gökevler,1.0,AVCILAR,565,İSTASYON DIŞI ARIZA & NORMAL ÇALIŞMA,İSTASYON DIŞI ARIZA,411.0,Normal Çalışma
8,33164018,80155,20250101,05:01:23,2401.0,10,2025-01-01 05:34:23.000,2025-01-01 05:34:57.858,2025-01-01 05:34:53.429,445,DİĞER OLAY,411,Normal Çalışma,0,2025-01-01,2025,1,1,1,1,0,900122.0,DARÜLACEZE PERPA,ISTASYON,KAPALI,Var,İstanbul,Kağıthane,Talatpaşa,1.0,ZİNCİRLİKUYU,578,DİĞER OLAY & NORMAL ÇALIŞMA,DİĞER OLAY,411.0,Normal Çalışma
9,33164019,80166,20250101,21:01:13,8798.0,22,2025-01-01 21:28:13.000,2025-01-01 21:36:15.582,2025-01-01 21:36:07.489,433,İSTASYON İÇİ ARIZA,99,Tek Şeritten Çalışma,0,2025-01-01,2025,1,1,1,1,0,900382.0,HARAMİDERE,ISTASYON,KAPALI,Var,İstanbul,Esenyurt,Güzelyurt,1.0,AVCILAR,501,İSTASYON İÇİ ARIZA & TEK ŞERİTTEN ÇALIŞMA,İSTASYON İÇİ ARIZA,99.0,Tek Şeritten Çalışma

In [6]:
df_yolculuk = pd.read_csv("C:/Users/asus/Desktop/Datathon/YOLCULUK/DATA/yolculuk_temiz_final.csv", encoding="utf-8-sig", low_memory=False, nrows=10)
print(f"Satir: 10,000,000+ | Kolon: {len(df_yolculuk.columns)}")
df_yolculuk

Satir: 10,000,000+ | Kolon: 89

,FID,GECISID,DMEDYASERINO,GECISZAMANI,DGECISTURU,DAKTARMATIPI,DGECISKATEGORI,DGECISTIPI,DMEDYATIPI,DBILETTIPI,DBILETKATEGORI,SONRAKIHATDAKIKAFARKI,SIDULASIMTURU,SIDOPERATOR,SIDTARIH,SIDARAC,SIDHAT,SIDONCEKIOPERATOR,SIDONCEKIHAT,SIDDURAK,TARIH,YIL,AY,GUN,CEYREK,HAFTA,HAFTASONU,GUNCEL_HATKODU,GUNCEL_HATADI,GUNCEL_HATGARAJI,GUNCEL_HATCINSI,GUNCEL_HATUZUNLUK,GUNCEL_HATILCE,GUNCEL_HATSURESI,GUNCEL_HAT_DURUM,ONCEKI_HATKODU,ONCEKI_HATADI,ONCEKI_HATGARAJI,ONCEKI_HATCINSI,ONCEKI_HATUZUNLUK,ONCEKI_HATILCE,ONCEKI_HAT_SURESI,ONCEKI_HAT_DURUM,KAPINO,MARKA,MODEL,MODELYILI,OPERATORID,OPERATORADI,KAPASITE,YAKITTURU,GARAJ,ARACBOYU,ARACCINSI,USTOPERATORADI,ARACTIPI,GARAJKODU,KOLTUKSAYISI,AZAMIKISISAYI,EMISYON,ENGELLI,TASITGENISLIK,TASITYUKSEKLIK,TASITUZUNLUK,TASITUZUNLUKBIRIMI,ULASIMTURU_KOD,ULASIMTURU_TANIM,DURAKKODU,DURAKADI,DURAKTIPI,FIZIKIDURUM,ENGELLIRAMPA,IL,ILCE,MAHALLE,DURAK_DURUM,YONBILGISI,GUNCEL_KILAVUZID,GUNCEL_KILAVUZDETAYID,GUNCEL_OPERATOR_TANIM,GUNCEL_OPERATOR_TANIMDETAY,GUNCEL_USTOPERATOR,GUNCEL_OPERATOR,ONCEKI_KILAVUZID,ONCEKI_KILAVUZDETAYID,ONCEKI_OPERATOR_TANIM,ONCEKI_OPERATOR_TANIMDETAY,ONCEKI_USTOPERATOR,ONCEKI_OPERATOR
0,2520925202,111197187811,mzz41N9N69xxVm,2025-01-01 16:40:03.000,İndirimli1 Kontür,Normal,Kontürlü,İNDİRİMLİ 1 KONTÖR,İstanbulKart,INDIRIMLI1,Öğrenci,0,2,494,20250101,880,760,549,0,8569,2025-01-01,2025,1,1,1,1,0,42T,BAHÇEKÖY - BALTALİMANI,SULTANGAZİ GARAJI,ÖHO,17788.66,Sarıyer,5071.42,1.0,Aktarmasız,Aktarmasız,Aktarmasız,Aktarmasız,0.00,Aktarmasız,0.00,0.0,A1880,OTOKAR,GÜLERYÜZ COBRA GD 272,2025.0,5,İstanbul Halk Ulaşım,92.0,MOTORIN,SULTANGAZIGARAJI,12.0,Solo -12m,ÖHO,Otobüs,G_STGZ,29.0,94.0,EEV,UYGUN,2.54,3.15,12.0,M,LASTİK TEKER,LASTİK TEKER,113112,BAHÇEKÖY,CCMODERN,KAPALI,Bilinmiyor,İstanbul,Sarıyer,Bahçeköy Merkez,1.0,SON DURAK,4,139,İSTANBUL HALK ULAŞIM SAN.TİC.AŞ.,İSTANBUL HALK ULAŞIM SAN.TİC.AŞ.,ÖHO,İstanbul Halk Ulaşım,4.0,240.0,İBB TOPLU ULAŞIM HİZMETLERİ MÜDÜRLÜĞÜ,ELİT TOPLU ULAŞIM HİZMETLERİ SANAYİ TİCARET AN...,KOOP,İst Elit Kooperatif
1,2520927706,111196190911,mzmVxxQp7N981m,2025-01-01 14:58:13.000,İndirimli2 Kontür,Aktarma,Kontürlü,İNDİRİMLİ 2 AKTARMA,İstanbulKart,INDIRIMLI2,Öğretmen,59,2,494,20250101,4411,760,549,757,7865,2025-01-01,2025,1,1,1,1,0,42T,BAHÇEKÖY - BALTALİMANI,SULTANGAZİ GARAJI,ÖHO,17788.66,Sarıyer,5071.42,1.0,40B,SARIYER - BEŞİKTAŞ,SULTANGAZİ GARAJI,KARMA,22869.78,Sarıyer,6745.18,1.0,A5411,OTOKAR,GÜLERYÜZ,2015.0,5,İstanbul Halk Ulaşım,96.0,MOTORIN,SULTANGAZIGARAJI,12.0,Solo -12m,ÖHO,Otobüs,G_STGZ,29.0,94.0,EEV,UYGUN,2.54,3.15,12.0,M,LASTİK TEKER,LASTİK TEKER,112261,TERSANE,ISTASYON,FULL KAPALI,Yok,İstanbul,Sarıyer,İstinye,1.0,BEŞİKTAŞ,4,139,İSTANBUL HALK ULAŞIM SAN.TİC.AŞ.,İSTANBUL HALK ULAŞIM SAN.TİC.AŞ.,ÖHO,İstanbul Halk Ulaşım,4.0,240.0,İBB TOPLU ULAŞIM HİZMETLERİ MÜDÜRLÜĞÜ,ELİT TOPLU ULAŞIM HİZMETLERİ SANAYİ TİCARET AN...,KOOP,İst Elit Kooperatif
2,2520928461,111197773111,mzzzR91p7Q26Vm,2025-01-01 17:52:22.000,İndirimli1 Abonman,Normal,Abonman,İNDİRİMLİ 1 ABONMAN,İstanbulKart,INDIRIMLI1,Öğrenci,65,2,494,20250101,4411,760,549,0,7728,2025-01-01,2025,1,1,1,1,0,42T,BAHÇEKÖY - BALTALİMANI,SULTANGAZİ GARAJI,ÖHO,17788.66,Sarıyer,5071.42,1.0,Aktarmasız,Aktarmasız,Aktarmasız,Aktarmasız,0.00,Aktarmasız,0.00,0.0,A5411,OTOKAR,GÜLERYÜZ,2015.0,5,İstanbul Halk Ulaşım,96.0,MOTORIN,SULTANGAZIGARAJI,12.0,Solo -12m,ÖHO,Otobüs,G_STGZ,29.0,94.0,EEV,UYGUN,2.54,3.15,12.0,M,LASTİK TEKER,LASTİK TEKER,113103,KÖY YOLU,İETTBAYRAK,AÇIK,Yok,İstanbul,Sarıyer,Bahçeköy Merkez,1.0,BAHÇEKÖY,4,139,İSTANBUL HALK ULAŞIM SAN.TİC.AŞ.,İSTANBUL HALK ULAŞIM SAN.TİC.AŞ.,ÖHO,İstanbul Halk Ulaşım,4.0,240.0,İBB TOPLU ULAŞIM HİZMETLERİ MÜDÜRLÜĞÜ,ELİT TOPLU ULAŞIM HİZMETLERİ SANAYİ TİCARET AN...,KOOP,İst Elit Kooperatif
3,2520928535,111197264111,mzNW9zmNWQzWVm,2025-01-01 16:56:25.000,İndirimli1 Abonman,Normal,Abonman,İNDİRİMLİ 1 ABONMAN,İstanbulKart,INDIRIMLI1,Öğrenci,0,2,494,20250101,4411,760,494,760,6773,2025-01-01,2025,1,1,1,1,0,42T,BAHÇEKÖY - BALTALİMANI,SULTANGAZİ GARAJI,ÖHO,17788.66,Sarıyer,5071.42,1.0,42T,BAHÇEKÖY - BALTALİMANI,SULTANGAZİ GARAJI,ÖHO,17788.66,Sarıyer,5071.42,1.0,A5411,OTOKAR,GÜLERYÜZ,2015.0,5,İstanbul Halk Ulaşım,96.0,MOTORIN,SULTANGAZIGARAJI,12.0,Solo -12m,ÖHO,Otobüs,G_STGZ,29.0,94.0,EEV,UYGUN,2.54,3.15,12.0,M,LASTİK TEKER,LASTİK TEKER,112392,KİREÇBURNU,WALLMODERN,KAPALI,Bilinmiyor,İstanbul,Sarıyer,Kireçburnu,1.0,SARIYER,4,139,İSTANBUL HALK ULAŞIM SAN.TİC.AŞ.,İSTANBUL HALK ULAŞIM SAN.TİC.AŞ.,ÖHO,İstanbul Halk Ulaşım,4.0,139.0,İSTANBUL HALK ULAŞIM SAN.TİC.AŞ.,İSTANBUL HALK ULAŞIM SAN.TİC.AŞ.,ÖHO,İstanbul Halk Ulaşım
4,2520929070,111196934011,mzNz4Q1N6xzWVm,2025-01-01 16:12:59.000,Tam Abonman,Normal,Abonman,TAM ABONMAN,İstanbulKart,TAM,Tam Mavi Kart,0,2,494,20250101,4411,760,527,757,11242,2025-01-01,2025,1,1,1,1,0,42T,BAHÇEKÖY - BALTALİMANI,SULTANGAZİ GARAJI,ÖHO,17788.66,Sarıyer,5071.42,1.0,40B,SARIYER - BEŞİKTAŞ,SULTANGAZİ GARAJI,KARMA,22869.78,Sarıyer,6745.18,1.0,A5411,OTOKAR,GÜLERYÜZ,2015.0,5,İstanbul Halk Ulaşım,96.0,MOTORIN,SULTANGAZIGARAJI,12.0,Solo -12m,ÖHO,Otobüs,G_STGZ,29.0,94.0,EEV,UYGUN,2.54,3.15,12.0,M,LASTİK TEKER,LASTİK TEKER,112242,EMİRGAN,WALLMODERN,KAPALI,Var,İstanbul,Sarıyer,Emirgan,1.0,SARIYER,4,139,İSTANBUL HALK ULAŞIM SAN.TİC.AŞ.,İSTANBUL HALK ULAŞIM SAN.TİC.AŞ.,ÖHO,İstanbul Halk Ulaşım,4.0,204.0,BOĞAZİÇİ TESİS YÖNETİM HİZMETLERİ SANAYİ VE Tİ...,BOĞAZİÇİ TESİS YÖNETİM HİZMETLERİ SANAYİ VE Tİ...,Aktarmasız,Aktarmasız
5,2520929739,111198245211,mz9zz1RN7V981m,2025-01-01 18:38:51.000,Tam Kontür,Normal,Kontürlü,Tam Kontürlü Geçiş,İstanbulKart,TAM,Tam,0,2,494,20250101,5280,631,494,0,14876,2025-01-01,2025,1,1,1,1,0,43R,RUMELİ HİSARÜSTÜ - KABATAŞ,SULTANGAZİ GARAJI,KARMA,9778.67,Sarıyer,2668.78,1.0,Aktarmasız,Aktarmasız,Aktarmasız,Aktarmasız,0.00,Aktarmasız,0.00,0.0,A6280,OTOKAR,MERCEDES CONECTO,2015.0,5,İstanbul Halk Ulaşım,96.0,MOTORIN,SULTANGAZIGARAJI,12.0,Solo -12m,ÖHO,Otobüs,G_STGZ,29.0,94.0,EEV,UYGUN,2.54,3.15,12.0,M,LASTİK TEKER,LASTİK TEKER,184091,DENİZ MÜZESİ,WALLMODERN,FULL KAPALI,Var,İstanbul,Beşiktaş,Sinanpaşa,1.0,ORTAKÖY,4,139,İSTANBUL HALK ULAŞIM SAN.TİC.AŞ.,İSTANBUL HALK ULAŞIM SAN.TİC.AŞ.,ÖHO,İstanbul Halk Ulaşım,4.0,139.0,İSTANBUL HALK ULAŞIM SAN.TİC.AŞ.,İSTANBUL HALK ULAŞIM SAN.TİC.AŞ.,ÖHO,İstanbul Halk Ulaşım
6,2520930265,111198313211,mz22R6WpWW2mVm,2025-01-01 18:49:40.000,İndirimli2 Abonman,Normal,Abonman,İNDİRİMLİ 2 ABONMAN,İstanbulKart,INDIRIMLI2,Yaşlı,20,2,494,20250101,5280,631,517,729,5318,2025-01-01,2025,1,1,1,1,0,43R,RUMELİ HİSARÜSTÜ - KABATAŞ,SULTANGAZİ GARAJI,KARMA,9778.67,Sarıyer,2668.78,1.0,34A,CEVİZLİBAĞ - SÖĞÜTLÜÇEŞME,TOPKAPI(TT),METROBÜS,14086.25,Fatih,5043.46,1.0,A6280,OTOKAR,MERCEDES CONECTO,2015.0,5,İstanbul Halk Ulaşım,96.0,MOTORIN,SULTANGAZIGARAJI,12.0,Solo -12m,ÖHO,Otobüs,G_STGZ,29.0,94.0,EEV,UYGUN,2.54,3.15,12.0,M,LASTİK TEKER,LASTİK TEKER,113363,ZİNCİRLİKUYU METROBÜS,WALLMODERN,KAPALI,Bilinmiyor,İstanbul,Beşiktaş,Balmumcu,1.0,ETİLER,4,139,İSTANBUL HALK ULAŞIM SAN.TİC.AŞ.,İSTANBUL HALK ULAŞIM SAN.TİC.AŞ.,ÖHO,İstanbul Halk Ulaşım,4.0,158.0,İETT İŞLETMELERİ GENEL MÜDÜRLÜĞÜ,İETT METROBÜS,İETT,Metrobüs
7,2520931694,111194000111,mz22NV7Nm2981m,2025-01-01 07:19:03.000,İndirimli1 Abonman,Normal,Abonman,İNDİRİMLİ 1 ABONMAN,İstanbulKart,INDIRIMLI1,Öğrenci,589,2,494,20250101,940,760,495,928,1371,2025-01-01,2025,1,1,1,1,0,42T,BAHÇEKÖY - BALTALİMANI,SULTANGAZİ GARAJI,ÖHO,17788.66,Sarıyer,5071.42,1.0,36Z,CEBECİ-ZİNCİRLİKUYU,TOPKAPI(TT),İETT,17648.84,Sultangazi,5381.56,1.0,A1940,OTOKAR,MERCEDES CONECTO,2015.0,5,İstanbul Halk Ulaşım,96.0,MOTORIN,SULTANGAZIGARAJI,12.0,Solo -12m,ÖHO,Otobüs,G_STGZ,29.0,94.0,EEV,UYGUN,2.54,3.15,12.0,M,LASTİK TEKER,LASTİK TEKER,113351,ZİNCİRLİKUYU,WALLMODERN,KAPALI,Bilinmiyor,İstanbul,Şişli,Esentepe,1.0,BEŞİKTAŞ,4,139,İSTANBUL HALK ULAŞIM SAN.TİC.AŞ.,İSTANBUL HALK ULAŞIM SAN.TİC.AŞ.,ÖHO,İstanbul Halk Ulaşım,4.0,157.0,YENİ İSTANBUL HALK OTOBÜSLERİ A.Ş,YENİ İSTANBUL HALK OTOBÜSLERİ A.Ş,ÖHO,Yeni İstanbul Halk Otobüsleri
8,2520932563,111198100211,mzRWV87N72RWVm,2025-01-01 18:08:39.000,İndirimli2 Kontür,Normal,Kontürlü,İNDİRİMLİ 2 KONTÖR,İstanbulKart,INDIRIMLI2,Yaşlı,17,2,494,20250101,940,760,494,501,10131,2025-01-01,2025,1,1,1,1,0,42T,BAHÇEKÖY - BALTALİMANI,SULTANGAZİ GARAJI,ÖHO,17788.66,Sarıyer,5071.42,1.0,559C,RUMELİ HİSARÜSTÜ - TAKSİM,SULTANGAZİ GARAJI,ÖHO,9758.88,Sarıyer,2753.27,1.0,A1940,OTOKAR,MERCEDES CONECTO,2015.0,5,İstanbul Halk Ulaşım,96.0,MOTORIN,SULTANGAZIGARAJI,12.0,Solo -12m,ÖHO,Otobüs,G_STGZ,29.0,94.0,EEV,UYGUN,2.54,3.15,12.0,M,LASTİK TEKER,LASTİK TEKER,113512,BOĞAZİÇİ ÜNİVERSİTESİ,CCMODERNDR,KAPALI,Var,İstanbul,Sarıyer,Rumeli Hisarı,1.0,ZİNCİRLİKUYU,4,139,İSTANBUL HALK ULAŞIM SAN.TİC.AŞ.,İSTANBUL HALK ULAŞIM SAN.TİC.AŞ.,ÖHO,İstanbul Halk Ulaşım,4.0,139.0,İSTANBUL HALK ULAŞIM SAN.TİC.AŞ.,İSTANBUL HALK ULAŞIM SAN.TİC.AŞ.,ÖHO,İstanbul Halk Ulaşım
9,2520932603,111198305111,mz4897WN4Wz4Vm,2025-01-01 18:39:31.000,Tam Kontür,Aktarma,Kontürlü,Tam Aktarmalı Geçiş,İstanbulKart,TAM,Tam,10,2,494,20250101,940,760,495,519,4311,2025-01-01,2025,1,1,1,1,0,42T,BAHÇEKÖY - BALTALİMANI,SULTANGAZİ GARAJI,ÖHO,17788.66,Sarıyer,5071.42,1.0,DT1,ORTAKÖY - TAKSİM,SULTANGAZİ GARAJI,KARMA,18226.66,Beşiktaş,2645.80,1.0,A1940,OTOKAR,MERCEDES CONECTO,2015.0,5,İstanbul Halk Ulaşım,96.0,MOTORIN,SULTANGAZIGARAJI,12.0,Solo -12m,ÖHO,Otobüs,G_STGZ,29.0,94.0,EEV,UYGUN,2.54,3.15,12.0,M,LASTİK TEKER,LASTİK TEKER,112022,AKARETLER,CCMODERNDR,KAPALI,Bilinmiyor,İstanbul,Beşiktaş,Sinanpaşa,1.0,EMİNÖNÜ,4,139,İSTANBUL HALK ULAŞIM SAN.TİC.AŞ.,İSTANBUL HALK ULAŞIM SAN.TİC.AŞ.,ÖHO,İstanbul Halk Ulaşım,4.0,157.0,YENİ İSTANBUL HALK OTOBÜSLERİ A.Ş,YENİ İSTANBUL HALK OTOBÜSLERİ A.Ş,ÖHO,Yeni İstanbul Halk Otobüsleri

In [7]:
import pandas as pd

df_yolculuk = pd.read_csv("C:/Users/asus/Desktop/Datathon/panel_data/temiz_veri/yolcu_gunluk_doluluk.csv", low_memory=False)
print(f"Satır: {len(df_yolculuk):,} | Kolon: {len(df_yolculuk.columns)}")
df_yolculuk

Satır: 850,454 | Kolon: 14

,KAPINO,TARIH,YIL,AY,GUN,CEYREK,HAFTA,HAFTASONU,yolcu_sayisi,sefer_sayisi,KAPASITE,MODEL,MODELYILI,doluluk_orani
0,A1203,2025-01-01,2025,1,1,1,1,0,4,5.0,31.0,BMC,2012.0,0.129
1,A1203,2025-01-02,2025,1,2,1,1,0,6,4.0,31.0,BMC,2012.0,0.194
2,A1203,2025-01-03,2025,1,3,1,1,0,3,4.0,31.0,BMC,2012.0,0.097
3,A1203,2025-01-04,2025,1,4,1,1,1,7,5.0,31.0,BMC,2012.0,0.226
4,A1203,2025-01-05,2025,1,5,1,1,1,8,5.0,31.0,BMC,2012.0,0.258
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
850449,T5924,2025-06-24,2025,6,24,2,25,0,2,6.0,0.0,AVENUE LF CNG,2014.0,inf
850450,T5924,2025-06-25,2025,6,25,2,26,0,2,6.0,0.0,AVENUE LF CNG,2014.0,inf
850451,T5924,2025-06-26,2025,6,26,2,26,0,2,7.0,0.0,AVENUE LF CNG,2014.0,inf
850452,T5924,2025-06-27,2025,6,27,2,26,0,4,10.0,0.0,AVENUE LF CNG,2014.0,inf
850453,T5924,2025-06-30,2025,6,30,2,26,0,4,8.0,0.0,AVENUE LF CNG,2014.0,inf

In [8]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', 50)

df_sefer = pd.read_csv("C:/Users/asus/Desktop/Datathon/panel_data/temiz_veri/sefer_temiz.csv", low_memory=False)
print(f"Satır: {len(df_sefer):,} | Kolon: {len(df_sefer.columns)}")
df_sefer.sample(20).reset_index(drop=True)

Satır: 10,162,086 | Kolon: 51

,BASLANGICZAMANI,BITISZAMANI,PLANLANANBASLANGICZAMANI,TAHMINIBITISZAMANI,TOPLAMKM,GUZERGAHUZUNLUK,PLANLANANGUZERGAHSURE,HATILKSONZAIDURUMU,SEFERSIRASI,SEFERSIRATIPI,SONRAKISEFERBASLAMAZAMANI,YARIDAKALANDURAKKODU,GERCEKLESENGUZERGAHUZUNLUK,GERCEKLESENGUZERGAHSURE,TARIH,YIL,AY,GUN,CEYREK,HAFTA,HAFTASONU,HATKODU,HATADI,HATGARAJI,HATCINSI,HATUZUNLUK,HATILCE,HATSURESI,GUZERGAHKODU,GUZERGAHADI,YON,KAPINO,MARKA,MODEL,MODELYILI,KAPASITE,YAKITTURU,ARAC_GARAJ,ARACCINSI,USTOPERATORADI,ARACTIPI,SICILNO,PERSONEL_TIP,PERSONEL_MESLEK,GARAJKODU,GARAJADI,GARAJ_ILCE,OPERATOR_TANIMDETAY,GOREV_DURUM_TANIMDETAY,GOREV_TIPI_TANIMDETAY,DURUM_DEGISIKLIK_TANIMDETAY
0,NaN,NaN,2025-02-03 10:40:00,NaN,0.000000,28575.98,4148.14,NaN,NaN,NaN,NaN,NaN,0.00,0.00,2025-02-03,2025,2,3,1,5,0,320A,SULTANBEYLİ MİMARSİNAN / SAMANDIRA - ÜSKÜDAR,SARIGAZIGARAJI,KARMA,35111.53,Sultanbeyli,9135.54,320A_D_D0,HAREM PERONLAR - BATTALGAZİ MAHALLESİ,DÖNÜŞ,C4866,NaN,GÜLERYÜZ COBRA GD 272,2025.0,92.0,NaN,NaN,Solo -12m,KOOP,NaN,P_55532,IETT,Şoför,NaN,NaN,NaN,İST HALK OTOBÜS,İptal,Planlı Görev,OtobusYoklugu
1,2025-03-17 06:32:27,2025-03-17 07:18:32,2025-03-17 06:33:00,2025-03-17 07:42:55,24731.567164,16783.18,2422.47,NaN,1.0,ILK_SEFER,2025-03-17 08:06:54,NaN,18340.29,2422.47,2025-03-17,2025,3,17,1,11,0,559C,RUMELİ HİSARÜSTÜ - TAKSİM,SULTANGAZİ GARAJI,ÖHO,9758.88,Sarıyer,2753.27,559C_G_D3659,RUMELİ HİSARÜSTÜ - PARK OTEL,GİDİŞ,A5477,NaN,AKIA ULTRA LF12,2016.0,99.0,NaN,NaN,Solo -12m,ÖHO,NaN,P_19997,IETT,Şoför,NaN,NaN,NaN,İstanbul Halk Ulaşım Tic.A.Ş,Tamamlandı,Planlı Görev,NaN
2,2025-02-14 18:15:46,2025-02-14 19:45:16,2025-02-14 18:15:00,2025-02-14 19:10:56,28175.970978,28390.46,4121.22,NaN,8.0,ARA_SEFER,2025-02-14 20:01:53,NaN,28390.46,4121.22,2025-02-14,2025,2,14,1,7,0,122M,ŞAHİNBEY - MECİDİYEKÖY,SARIGAZIGARAJI,İETT,28398.39,Çekmeköy,8352.58,122M_G_D0,ŞEHİT ŞAHİNBEY - MECİDİYEKÖY MEZARLIK,GİDİŞ,O6714,OTOKAR,KENT 290LF,2013.0,94.0,MOTORIN,Sarıgazi,SOLO,İETT,Otobüs,P_28545,IETT,Şoför,G_SRG,SARIGAZIGARAJI,Sancaktepe,İETT,Tamamlandı,Planlı Görev,NaN
3,2025-01-22 21:55:31,2025-01-22 22:38:48,2025-01-22 21:55:00,2025-01-22 22:20:48,14238.165799,11571.25,1679.70,NaN,7.0,ARA_SEFER,2025-01-22 22:40:26,NaN,11571.25,1679.70,2025-01-22,2025,1,22,1,4,0,91E,GÖZTEPE MAHALLESİ - AKSARAY,IKITELLIGARAJI,ÖHO,11995.41,Bağcılar,3534.59,91E_G_D0,GÖZTEPE MAHALLESİ - AKSARAY RİNG,GİDİŞ,A1467,NaN,AKIA,2016.0,99.0,NaN,NaN,Solo -12m,ÖHO,NaN,P_58240,IETT,Şoför,NaN,NaN,NaN,İstanbul Halk Ulaşım Tic.A.Ş,Tamamlandı,Planlı Görev,NaN
4,2025-05-22 10:47:52,2025-05-22 13:45:43,2025-05-22 10:48:00,2025-05-22 11:57:28,39836.218858,39269.03,5700.36,NaN,3.0,ARA_SEFER,2025-05-22 13:09:00,NaN,39274.82,5700.36,2025-05-22,2025,5,22,2,21,0,76D,BAHÇEŞEHİR / ESENKENT - TAKSİM,IKITELLIGARAJI,ÖÇK,39337.49,Başakşehir,11421.97,76D_G_D0,BAHÇEŞEHİR - GÜMÜŞSUYU PERON,GİDİŞ,B4306,BMC,PROCITY TR,2017.0,97.0,MOTORIN,IKITELLIGARAJI,SOLO,İETT,Otobüs,P_58881,IETT,Şoför,G_IKT,IKITELLIGARAJI,Küçükçekmece,İETT,Tamamlandı,Planlı Görev,NaN
5,NaN,NaN,2025-05-09 19:05:00,2025-05-09 19:46:44,0.000000,13914.87,2019.90,NaN,10.0,ARA_SEFER,2025-05-09 07:36:24,NaN,13914.87,2019.90,2025-05-09,2025,5,9,2,19,0,50Y,ALİBEYKÖY - YENİKAPI,KAGITHANEGARAJI,KARMA,14647.57,Eyüpsultan,4114.98,50Y_D_D0,YENİKAPI ETKİNLİK ALANI - ALİBEYKÖY METRO,DÖNÜŞ,A9479,AKIA,ULTRA LF12,2024.0,0.0,NaN,Topkapı,SOLO,İETT,Otobüs,P_57184,IETT,Şoför,G_TPK,TOPKAPI(TT),Fatih,İETT,Tamamlandı,Planlı Görev,NaN
6,2025-05-24 19:10:42,2025-05-24 20:29:00,2025-05-24 19:10:00,2025-05-24 19:54:48,18802.100045,19286.35,2799.67,NaN,9.0,ARA_SEFER,2025-05-24 20:54:35,NaN,19286.35,2799.67,2025-05-24,2025,5,24,2,21,1,41C,AYAZAĞA - SARIYER,SULTANGAZİ GARAJI,KARMA,19286.35,Sarıyer,5545.31,41C_G_D0,AYAZAĞA - SARIYER,GİDİŞ,O4155,OTOKAR,KENT 290LF,2013.0,94.0,MOTORIN,SULTANGAZIGARAJI,SOLO,İETT,Otobüs,P_36005,IETT,Şoför,G_STGZ,SULTANGAZİ GARAJI,Sultangazi,İETT,Tamamlandı,Planlı Görev,NaN
7,2025-06-12 08:34:37,2025-06-12 09:10:23,2025-06-12 08:26:00,2025-06-12 09:04:23,16283.375787,16606.66,2410.65,NaN,2.0,ARA_SEFER,2025-06-12 09:37:00,NaN,16606.66,2410.65,2025-06-12,2025,6,12,2,24,0,TM4,GÖKTÜRK- ALİBEYKÖY,KAGITHANEGARAJI,KARMA,16606.66,Kağıthane,4925.62,TM4_G_D0,KÖPRÜBAŞI MAHALLESİ - ALİBEYKÖY METRO,GİDİŞ,B7269,NaN,TEMSA,2012.0,31.0,NaN,NaN,Solo -12m,KOOP,NaN,P_65115,IETT,Şoför,NaN,NaN,NaN,İST HALK OTOBÜS,Tamamlandı,Planlı Görev,NaN
8,2025-03-14 07:11:00,2025-03-14 07:33:01,2025-03-14 07:08:00,NaN,6464.385267,7622.67,1106.52,NaN,1.0,ILK_SEFER,NaN,NaN,7249.35,1106.52,2025-03-14,2025,3,14,1,11,0,8A,BATI ATAŞEHİR / FİKİRTEPE - KADIKÖY,ANADOLUGARAJI,KARMA,10818.61,Ataşehir,3403.24,8A_G_D4360,BATI ATAŞEHİR PERONLAR - BATI ATAŞEHİR PERONLAR,GİDİŞ,C4706,NaN,TEMSA,2012.0,31.0,NaN,NaN,Solo -12m,KOOP,NaN,P_16846,IETT,Şoför,NaN,NaN,NaN,İST HALK OTOBÜS,Tamamlandı,Planlı Görev,NaN
9,2025-06-27 15:25:22,2025-06-27 16:10:59,2025-06-27 15:25:00,2025-06-27 15:49:52,17900.778081,17788.66,2582.20,NaN,9.0,ARA_SEFER,2025-06-27 16:25:02,NaN,17788.66,2582.20,2025-06-27,2025,6,27,2,26,0,42T,BAHÇEKÖY - BALTALİMANI,SULTANGAZİ GARAJI,ÖHO,17788.66,Sarıyer,5071.42,42T_G_D0,BAHÇEKÖY - AHMET CELALETTİN PAŞA CAMİ,GİDİŞ,A7485,NaN,GÜLERYÜZ COBRA GD 272,2017.0,96.0,NaN,NaN,Solo -12m,ÖHO,NaN,P_57576,IETT,Şoför,NaN,NaN,NaN,İstanbul Halk Ulaşım Tic.A.Ş,Tamamlandı,Planlı Görev,NaN
10,2025-05-20 15:24:11,2025-05-20 16:46:36,2025-05-20 15:25:00,2025-05-20 16:22:34,22937.831611,22865.82,3319.26,NaN,7.0,ARA_SEFER,2025-05-20 17:05:04,NaN,23591.75,3319.26,2025-05-20,2025,5,20,2,20,0,40B,SARIYER - BEŞİKTAŞ,SULTANGAZİ GARAJI,KARMA,22869.78,Sarıyer,6745.18,40B_D_D0,BEŞİKTAŞ PERONLAR - SARIYER,DÖNÜŞ,B1269,NaN,MERCEDES CONECTO,2025.0,105.0,NaN,NaN,Solo -12m,KOOP,NaN,P_57396,IETT,Şoför,NaN,NaN,NaN,ELİT KARAYOLU YOLCU TAŞIMA,Tamamlandı,Planlı Görev,NaN
11,2025-02-14 08:45:16,2025-02-14 09:23:38,2025-02-14 08:45:00,2025-02-14 09:10:45,8673.652777,8466.82,1229.06,NaN,3.0,ARA_SEFER,2025-02-14 09:52:34,NaN,8466.82,1229.06,2025-02-14,2025,2,14,1,7,0,30M,BEŞİKTAŞ - MECİDİYEKÖY,SULTANGAZİ GARAJI,KARMA,8466.82,Beşiktaş,1229.06,30M_G_D0,BEŞİKTAŞ PERONLAR - MECİDİYEKÖY VİYADÜK,GİDİŞ,B7120,NaN,GÜLERYÜZ COBRA GD 272,2013.0,98.0,NaN,NaN,Solo -12m,ÖHO,NaN,P_16526,IETT,Şoför,NaN,NaN,NaN,Yeni İstanbul Özel Halk Otobüsleri Tic.A.Ş,Tamamlandı,Planlı Görev,NaN
12,2025-06-03 11:31:00,2025-06-03 12:40:38,2025-06-03 11:32:00,2025-06-03 12:16:20,32095.507872,30405.27,4389.29,NaN,3.0,ARA_SEFER,2025-06-03 13:03:09,NaN,30405.27,4389.29,2025-06-03,2025,6,3,2,22,0,18D,SULTANBEYLİ - KADIKÖY,KURTKOYGARAJI,ÖHO,32347.24,Sultanbeyli,9175.99,18D_G_D0,SULTANBEYLİ PERONLAR - KADIKÖY,GİDİŞ,D6407,NaN,GÜLERYÜZ,2023.0,76.0,NaN,NaN,Çift katlı,ÖHO,NaN,P_24604,IETT,Şoför,NaN,NaN,NaN,ÇİFT KATLILAR,Tamamlandı,Planlı Görev,NaN
13,2025-05-08 20:39:59,2025-05-08 22:08:43,2025-05-08 20:40:00,2025-05-08 21:49:22,26345.678936,27394.58,3976.62,NaN,6.0,ARA_SEFER,2025-05-08 23:30:49,NaN,28732.07,3976.62,2025-05-08,2025,5,8,2,19,0,TM15,CEBECİ PERONLAR - ALİBEYKÖY,TOPKAPI(TT),KARMA,15430.25,Gaziosmanpaşa,3967.47,TM15_G_D5266,CEBECİ PERONLAR - ALİBEYKÖY METRO,GİDİŞ,B3472,NaN,BMC,2018.0,98.0,NaN,NaN,Solo -12m,KOOP,NaN,P_31590,IETT,Şoför,NaN,NaN,NaN,ELİT KARAYOLU YOLCU TAŞIMA,Tamamlandı,Planlı Görev,NaN
14,2025-05-11 20:30:45,2025-05-11 21:39:40,2025-05-11 20:15:00,2025-05-11 21:28:14,18632.376503,19286.35,2799.67,NaN,11.0,ARA_SEFER,2025-05-11 21:44:00,NaN,19286.35,2799.67,2025-05-11,2025,5,11,2,19,1,41AT,AYAZAĞA - DAVUTPAŞA Y.T.Ü,SULTANGAZİ GARAJI,KARMA,25945.66,Sarıyer,7973.57,41C_G_D4631,AYAZAĞA - SARIYER,GİDİŞ,B2543,NaN,BMC,2015.0,98.0,NaN,NaN,Solo -12m,KOOP,NaN,P_36367,IETT,Şoför,NaN,NaN,NaN,ELİT KARAYOLU YOLCU TAŞIMA,Tamamlandı,Planlı Görev,NaN
15,2025-01-08 06:00:31,2025-01-08 06:36:26,2025-01-08 06:00:00,2025-01-08 06:31:59,20898.982694,20621.93,2993.49,NaN,1.0,ILK_SEFER,2025-01-08 06:50:00,NaN,20621.93,2993.49,2025-01-08,2025,1,8,1,2,0,336Y,CEBECİ - YENİKAPI MARMARAY,TOPKAPI(TT),İETT,20592.29,Sultangazi,6163.12,336Y_G_D0,CEBECİ PERONLAR - YENİKAPI ETKİNLİK ALANI,GİDİŞ,O5946,OTOKAR,KENT 290LF,2013.0,94.0,MOTORIN,SULTANGAZIGARAJI,SOLO,İETT,Otobüs,P_56132,IETT,Şoför,G_STGZ,SULTANGAZİ GARAJI,Sultangazi,İETT,Tamamlandı,Planlı Görev,NaN
16,2025-04-23 12:30:59,2025-04-23 13:38:54,2025-04-23 12:30:00,2025-04-23 13:14:49,18660.792816,19035.86,2763.26,NaN,4.0,ARA_SEFER,2025-04-23 13:59:10,NaN,19035.86,2763.26,2025-04-23,2025,4,23,2,17,0,19T,FERHATPAŞA - KADIKÖY,ANADOLUGARAJI,KARMA,19042.47,Ataşehir,5325.16,19T_G_D0,ATATÜRK BULVARI - KADIKÖY,GİDİŞ,C1576,NaN,TEMSA AVENUE LF,2014.0,106.0,NaN,NaN,Solo -12m,ÖHO,NaN,P_22192,IETT,Şoför,NaN,NaN,NaN,ÖZULAŞ A.Ş,Tamamlandı,Planlı Görev,NaN
17,2025-03-05 15:20:39,2025-03-05 16:24:51,2025-03-05 15:20:00,2025-03-05 16:09:50,14572.565379,14983.53,2161.98,NaN,7.0,ARA_SEFER,2025-03-05 17:25:10,NaN,15101.13,2161.98,2025-03-05,2025,3,5,1,10,0,88,SULTANGAZİ PERON - TOPKAPI,TOPKAPI(TT),İETT,15827.95,Sultangazi,4406.22,88_G_D0,SULTANGAZİ PERONLAR - TOPKAPI,GİDİŞ,O3561,OTOKAR,KENT 290LF,2013.0,94.0,MOTORIN,SULTANGAZIGARAJI,SOLO,İETT,Otobüs,P_56387,IETT,Şoför,G_STGZ,SULTANGAZİ GARAJI,Sultangazi,İETT,Tamamlandı,Planlı Görev,NaN
18,2025-02-25 17:40:27,2025-02-25 18:12:37,2025-02-25 17:40:00,2025-02-25 17:56:07,10559.307880,11002.25,1597.10,NaN,12.0,ARA_SEFER,2025-02-25 18:32:02,NaN,11002.25,1597.10,2025-02-25,2025,2,25,1,8,0,MR40,K.S.S. HASTANESİ - ATAKENT - HALKALI MARMARAY,IKITELLIGARAJI,OAŞ,13435.52,Küçükçekmece,4112.91,MR40_D_D0,GÜMRÜK - KANUNİ SULTAN SÜLEYMAN,DÖNÜŞ,A7562,NaN,BMC PROCITY 285,2015.0,98.0,NaN,NaN,Solo -12m,ÖHO,NaN,P_32497,IETT,Şoför,NaN,NaN,NaN,MAVİ MARMARA ULAŞIM A.Ş,Tamamlandı,Planlı Görev,NaN
19,2025-02-17 21:15:19,2025-02-17 21:40:46,2025-02-17 21:15:00,2025-02-17 21:31:11,8150.889602,7913.99,1148.81,NaN,8.0,ARA_SEFER,2025-02-17 21:51:45,NaN,8703.40,1148.81,2025-02-17,2025,2,17,1,7,0,50S,ALİBEYKÖY - ŞİŞLİ,KAGITHANEGARAJI,KARMA,8752.66,Eyüpsultan,2809.44,50S_G_D0,ALİBEYKÖY METRO - ŞİŞLİ MERKEZ,GİDİŞ,A1862,NaN,TEMSA,2014.0,106.0,NaN,NaN,Solo -12m,ÖHO,NaN,P_51177,IETT,Şoför,NaN,NaN,NaN,MAVİ MARMARA ULAŞIM A.Ş,Tamamlandı,Planlı Görev,NaN

In [9]:
import pandas as pd

df = pd.read_csv("C:/Users/asus/Desktop/Datathon/panel_data/temiz_veri/ariza_model.csv", low_memory=False)

null_sayisi = df.isnull().sum()
null_var = null_sayisi[null_sayisi > 0]
null_oran = (null_var / len(df) * 100).round(1)

print(f"Toplam satır: {len(df):,}")
print(pd.DataFrame({'null_sayisi': null_var, 'oran_%': null_oran}))

Toplam satır: 68,721
Empty DataFrame
Columns: [null_sayisi, oran_%]
Index: []

In [10]:
import pandas as pd

df = pd.read_csv("C:/Users/asus/Desktop/Datathon/panel_data/temiz_veri/ariza_temiz.csv", low_memory=False)

null_sayisi = df.isnull().sum()
null_var = null_sayisi[null_sayisi > 0]
null_oran = (null_var / len(df) * 100).round(1)

print(f"Toplam satır: {len(df):,}")
print(pd.DataFrame({'null_sayisi': null_var, 'oran_%': null_oran}))

Toplam satır: 78,271
                null_sayisi  oran_%
KAPASITE                 39     0.0
TOPLAM_SURE_DK        17396    22.2